### ISSUE TITLE
Add ability to disable the summary

### ISSUE THREAD

**Issue by xSAVIKx** [coderabbitai/ai-pr-reviewer#271]
Hey, thx for the awesome GH action.

We have a use case where we don't really want the summary but want only the per-file review. It'd be great to be able to disable the summary with an option.

**Comment by harjotgill** [comment]
This is going to be tricky in the current implementation.

The summary comment has hidden state (within markdown comment blocks) to track - 
1. Commit Ids reviewed so far
2. Raw summary for incremental reviews 
3. Short summary for interactive chat with the bot and file reviews 

In addition, summary stage classifies trivial changes and skips review if needed.

**Comment by xSAVIKx** [comment]
Is it maybe possible to add an option to hide the whole comment under a summary/details block?

Also, just as an idea, I know GH actions/apps use Wiki pages to store their state when smth like you mentioned is done, maybe that can be an option?

**Comment by harjotgill** [comment]
This can't be done in the current design. Closing ticket.
