### ISSUE TITLE
Remove opinionated text wording comments

### ISSUE THREAD

**Issue by trisha** [coderabbitai/ai-pr-reviewer#310]
Some of my PRs are littered with comments such as these:
![image](https://github.com/coderabbitai/openai-pr-reviewer/assets/29530389/bc52f089-3a56-4e20-8378-ab215c0f0f15)

Email ends with a "Cheers" but is preceded by a list of order details that have colons:
![image](https://github.com/coderabbitai/openai-pr-reviewer/assets/29530389/efa6e4c2-77f8-4e93-bc37-be289bf807e2)

This is such a nit:
![image](https://github.com/coderabbitai/openai-pr-reviewer/assets/29530389/43e1be89-8ec2-4511-8654-8220541c05e4)

The ending message is already so short!!!! What else do you want from me?!
![image](https://github.com/coderabbitai/openai-pr-reviewer/assets/29530389/3d999531-2fb5-4e79-8ba3-2c6304cc5c71)

Like please, I already had someone from the business team copy edit the emails. Not looking for further wording feedback from the bot. 

There are two and a half amounts of the below screenshot, of these opinionated comments -- keep in mind this is what it looks like after I've manually resolved each one. The bot spams my PR and adds a lot of noise, in addition to making it more difficult to find comments from my teammates:
![image](https://github.com/coderabbitai/openai-pr-reviewer/assets/29530389/615f23ea-887f-4fbe-81ec-991f17ac9223)

**Comment by trisha** [comment]
Alternatively, would love a "max number of line-by-line comments" config setting and the prompt takes that number and asks the bot to only share its most important or bug-preventing comments

**Comment by jdnichollsc** [comment]
Hello folks, hope you're doing well! Do you have any plan to disable those comments?

Please let us know, thanks for your help!

**Comment by guritfaq** [comment]
Hi Guys , Great  feedback!  We have exciting news! We are launching a professional version of this open-source project, where we will be focusing our future development. We invite you to check out [Coderabbit.ai](http://coderabbit.ai/) to learn more.

We've taken note of your valuable input and have added these suggestions to our backlog. I will keep you in the loop as we roll out these new enhancements.

**Comment by harjotgill** [comment]
Closing ticket. All this has been configurable via System Prompt since day 1.

Please chat with the person who setup the GitHub Action to tweak the prompt to ignore such comments.
