### ISSUE TITLE
Add more context lines to each patch

### ISSUE THREAD

**Issue by pistachiomatt** [coderabbitai/ai-pr-reviewer#332]
Often, the PR reviewer will make false assumptions because it can only see a small amount of lines that have been changed in the file.

One common issue is it'll say "This variable isn't being used anywhere" when it in fact is, it's just referenced outside the hunk.

It would be useful to add a config to allow larger hunks/more context lines.

**Comment by guritfaq** [comment]
Hi @pistachiomatt , Thanks for the feedback.  We are launching a professional version of this open-source project, where we will be focusing our future development. We invite you to check out [Coderabbit.ai](http://coderabbit.ai/) to learn more.

We have noted this issue and plan on addressing this in the coming weeks.

**Comment by pistachiomatt** [comment]
Thanks great. Congrats!

**Comment by pistachiomatt** [comment]
Update this ticket when you get it. I'd be keen to switch over to your paid plan then (but not before because it's not very useful until that feature is built.)

**Comment by guritfaq** [comment]
Thank you. Will keep you posted.

**Comment by harjotgill** [comment]
Noise should be minimal outside the patch lines since we pushed prompt changes a few weeks back. In addition, the Pro version of CodeRabbit has better noise reduction, and we haven't seen these kinds of noisy comments lately. Closing ticket.
