### ISSUE TITLE
Not able to access GPT-4 API

### ISSUE THREAD

**Issue by autobotsaidemo** [coderabbitai/ai-pr-reviewer#420]
Hi, 
I am having access to GPT-Plus, but I am not able to access services via API. I get the error message below. Please help me with this issue.
Thank you.
"error": {
        "message": "The model `gpt-4` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.",
        "type": "invalid_request_error",
        "param": null,
        "code": "model_not_found"
    }

**Comment by harjotgill** [comment]
Please reach out to OpenAI. They probably have a waitlist.

**Comment by autobotsaidemo** [comment]
> Please reach out to OpenAI. They probably have a waitlist.

We already sent an email, but did not get any response. Any idea how to connect them quickly?
