### ISSUE TITLE
Node 16 deprecation in september

### ISSUE THREAD

**Issue by D3vJ3rry** [coderabbitai/ai-pr-reviewer#425]
Node 16 is being deprecated in September 2023. Your example action uses node 16 is that still the recommended version?
https://endoflife.date/nodejs#:~:text=The%20End%2Dof%2DLife%20date,1%20on%20September%2011th%2C%202023.

**Comment by harjotgill** [comment]
You can use this with the latest version. Cheers!

I don't think GitHub action has switched to Node 18 LTS yet - https://github.com/actions/runner-images/discussions/5429#discussioncomment-2614422

**Comment by D3vJ3rry** [comment]
Thank you! Will update to 18
