### ISSUE TITLE
`disable_review: true` still posts blank reviews.

### ISSUE THREAD

**Issue by johnboiles** [coderabbitai/ai-pr-reviewer#433]
For example:
<img width="934" alt="image" src="https://github.com/coderabbitai/ai-pr-reviewer/assets/218876/2d838e64-74dd-474a-ada8-614311cce792">

It correctly does not post any review comments it just posts these spammy comments.

**Comment by harjotgill** [comment]
Fixed in #434

**Comment by johnboiles** [comment]
Amazing! Thanks for the quick turnaround!!
