### ISSUE TITLE
Add support for GH suggestions

### ISSUE THREAD

**Issue by Tradunsky** [coderabbitai/ai-pr-reviewer#496]
Right now the code change suggestions are formatted with git patch format. You can only copy paste the change and use git patch apply to have it on PR.
<img width="528" alt="image" src="https://github.com/coderabbitai/ai-pr-reviewer/assets/4522842/e8b169cd-75db-4625-88da-2b3f3e86a71e">

GitHub PR supports faster code suggestions: select the code frame, click on suggestions or type:
<img width="545" alt="image" src="https://github.com/coderabbitai/ai-pr-reviewer/assets/4522842/32290c84-5266-4027-9967-43140c50e548">
which turns into a prompt message with buttons to commit changes:
<img width="530" alt="image" src="https://github.com/coderabbitai/ai-pr-reviewer/assets/4522842/997a6b51-4edb-40ed-9d13-bc9ef65f7675">

**Comment by guritfaq** [comment]
The problem is that committable suggestions become unreadable beyond a few lines, which is why we provide a copyable diff. We have, however, recently added committable suggestions along with a diff to our Pro version. Pro uses a different prompt from OSS.

**Comment by Tradunsky** [comment]
@guritfaq 
Do you think it would be enough to slightly modify the prompt to reformat the diff into GH suggestions?

I understand that a Pro version would have more robust features and it does make sense to have Pro version extend beyond standard offering. Just want to clarify that at this stage we are looking for Proof of Value for AI assisted code review, primarily it means that the base offering should be helpful and deliver on its purpose. When PoV is done, it does make sense to invest further into Pro version. 

I primarily see a missing opportunity here to proof value, because it is additional effort to comprehend and utilize the diff suggestions. In some cases, it would be just faster for people to post code suggestions to each other than dedicating time to diff decoding.

**Comment by guritfaq** [comment]
@Tradunsky Excuse the late reply. Committable suggestions were in the OSS and can be found in the commit history. 
The challenge is that our pro version has significantly diverged from the OSS, including the prompts and it is hard to move the changes over. We will eventually roll these changes over to OSS but that will take some time. 

We offer a free trial for the Pro version and can extend it if needed.
